/* ===== Configuração ===== */
const LOGO="assets/logo.svg", PRISM_V="assets/prism_v.jpg", MATTE_V="assets/matte_v.jpg";
const CAL_URL="https://cal.com/marioalves";
// Endpoint que recebe os leads (POST JSON). Vazio = não envia para lado nenhum.
// Ex.: "/api/lead" numa função serverless da Vercel que cria o contacto no HubSpot.
const LEAD_ENDPOINT="";
// Formulário de dúvidas: função serverless em api/contact.js, que envia a mensagem para CONTACT_EMAIL.
const CONTACT_ENDPOINT="/api/contact";
const CONTACT_EMAIL="hello@layerx.xyz";
// Envio do relatório PDF por email depois de a pessoa deixar o email: função serverless em api/report.js.
const REPORT_ENDPOINT="/api/report";
const LANGS=["pt","en"];

/* ===== Estrutura comum às duas línguas ===== */
// A ordem dos eixos é sempre esta, também nos vetores dos perfis de referência.
const AXIS_KEYS=["est","ado","pro","dad","tec","pes","gov","inv"];
// Pela mesma ordem de STR[lang].sectors. Os perfis de setor usam estas chaves.
const SECTOR_KEYS=["fin","ind","ret","tech","health","log","prof","pub","energy","tour","telco","other"];
// Metadados das perguntas, pela mesma ordem de STR[lang].questions.
const Q_META=[
 {id:"setor",profile:true,grid:true},{id:"dim",profile:true},{id:"funcao",profile:true},
 {ax:"est"},{ax:"est"},{ax:"ado"},{ax:"ado"},{ax:"pro"},{ax:"pro"},{ax:"dad"},{ax:"dad"},
 {ax:"tec"},{ax:"tec"},{ax:"pes"},{ax:"pes"},{ax:"gov"},{ax:"gov"},{ax:"inv"},{ax:"inv"},
 {ax:"ado",bonus:true},
];
const PTS=[0,33,67,100];
const band=v=>v<40?0:v<70?1:2;
const LEVEL_CUTS=[25,50,70,85,101];

// Reference profiles [est, ado, pro, dad, tec, pes, gov, inv], estimated from public positioning.
// Nomes genéricos têm versão por língua.
const COMPANIES=[
 ["Shopify",[95,95,80,85,90,85,65,85]],["Klarna",[95,85,90,85,90,70,60,90]],["Duolingo",[95,85,80,85,90,70,60,85]],
 ["JPMorgan Chase",[90,70,75,90,90,75,95,95]],["Siemens",[85,60,75,80,80,70,85,85]],["Moderna",[90,80,75,90,85,80,75,80]],
 ["IKEA",[70,55,55,70,70,70,70,65]],
 [{pt:"Scale-up SaaS típica",en:"Typical SaaS scale-up"},[80,85,65,75,85,70,55,70]],
 [{pt:"Startup tech típica",en:"Typical tech startup"},[60,85,50,55,75,55,20,40]],
 [{pt:"Banco tradicional",en:"Traditional bank"},[55,35,30,55,45,35,70,40]],
 [{pt:"Consultora tradicional",en:"Traditional consultancy"},[55,65,30,40,40,50,40,35]],
 [{pt:"Agência criativa",en:"Creative agency"},[45,80,35,30,40,55,20,30]],
 [{pt:"Retalhista tradicional",en:"Traditional retailer"},[35,30,20,40,40,25,30,25]],
 [{pt:"Organismo público",en:"Public body"},[30,20,15,30,25,20,50,20]],
 [{pt:"PME industrial típica",en:"Typical industrial SME"},[25,25,10,25,25,15,10,15]],
];
const SECTOR_PROFILES=[
 ["tech",[70,80,60,70,80,60,45,60]],["fin",[65,50,50,70,65,50,80,65]],["telco",[65,55,55,70,70,50,65,60]],
 ["energy",[55,40,45,60,55,40,65,50]],["prof",[55,65,35,45,45,50,45,40]],["ret",[45,40,35,50,50,35,35,35]],
 ["log",[40,30,35,45,40,25,30,30]],["ind",[40,30,30,40,40,30,30,30]],["health",[40,35,25,40,35,30,55,30]],
 ["pub",[30,25,15,30,25,20,50,20]],["tour",[30,35,20,30,30,20,25,20]],
];

/* ===== Conteúdo por língua ===== */
const STR={
pt:{
 htmlLang:"pt-PT",locale:"pt-PT",
 title:"AI Mirror · LayerX",
 metaDesc:"Diagnóstico gratuito: quão AI ready está a tua empresa? 20 perguntas, 8 eixos, o teu arquétipo e um plano de 90 dias.",
 ui:{
  langLabel:"Língua",navLabel:"Navegação principal",nav:{quiz:"AI Mirror",companies:"Empresas",countries:"Países"},
  rankingsTitle:"Rankings globais de adoção de IA",
  rankings:[["/rankings/empresas","Ranking · Empresas","Que grandes empresas estão mais avançadas em IA?","As 500 empresas do S&P 500 avaliadas pelo AIDE Index 2026."],
            ["/rankings/paises","Ranking · Países","Onde se usa mais IA no mundo?","147 economias no Microsoft AI Diffusion Report. Vê onde está Portugal."]],
  rankingsLink:"Ver ranking →",
  resumeKicker:"Diagnóstico em curso",resumeTitle:"Continua onde ficaste",
  resumeBody:(n,t)=>`Respondeste a ${n} de ${t} perguntas. As respostas ficam guardadas neste browser.`,
  resumeKickerDone:"Diagnóstico concluído",resumeTitleDone:"O teu resultado está guardado",
  resumeBodyDone:"Respondeste a todas as perguntas. As respostas ficam guardadas neste browser.",
  resumeContinue:"Continuar →",resumeSeeResult:"Ver resultado →",resumeRestart:"Recomeçar",
  eyebrow:"AI Mirror · Diagnóstico gratuito · LayerX",
  h1:'Quão <span class="gtext">AI ready</span> está a tua empresa?',
  lead:"20 perguntas, cerca de 4 minutos. No fim vês o perfil da tua empresa em 8 eixos, o teu arquétipo e com quem te pareces. Se quiseres, recebes também um relatório com um plano de ação.",
  companyLabel:"Nome da empresa (opcional, aparece no teu cartão)",
  companyPh:"Ex.: Metalúrgica do Norte",
  start:"Começar diagnóstico →",
  meta:["20 perguntas","8 eixos","7 arquétipos"],
  axesPreview:"Os 8 eixos · exemplo",axesPreviewAria:"Os 8 eixos medidos",
  tagProfile:"Perfil",tagBonus:"Bónus",
  back:"Anterior",home:"Início",keyHint:"1–4 para responder · ← voltar",
  computing:"A calcular os teus 8 eixos…",
  radarAria:"Radar dos 8 eixos",
  people:"pessoas",
  cardHead:"O MEU RESULTADO",scoreLbl:"AI Ready",closest:"Mais parecida com",compatible:"compatível",
  yourAxes:"Os teus 8 eixos",otherCompanies:"Outras empresas",nearSectors:"Setores próximos",
  superpower:"Superpoder",achilles:"Calcanhar de Aquiles",cardFootL:"Descobre o teu perfil",
  shareNote:"Tira um print ao cartão para partilhar no LinkedIn ou nas stories.",
  ctaText:"Queres transformar este diagnóstico num plano concreto? Fala 30 minutos com a equipa de AI Consulting da LayerX.",
  ctaBtn:"Marcar conversa ↗",redo:"↺ Refazer o diagnóstico",
  toc:[["Análise do teu arquétipo","O que caracteriza a empresa, o maior risco e onde focar"],
       ["Os 8 eixos em detalhe","Diagnóstico e recomendação para cada eixo"],
       null,
       ["Plano de 90 dias","Três passos, por ordem, a começar pelo eixo mais fraco"]],
  tocSector:s=>"Comparação com o setor "+s,tocBench:"Benchmark com empresas e setores",tocBenchSub:"Onde estás acima e abaixo da referência",
  reportReady:"O teu relatório está pronto",
  reportReadyP:n=>`Relatório em PDF, 3 páginas, com o plano de ação para ${n}.`,yourCompany:"a tua empresa",
  download:"Descarregar relatório PDF",
  reportTitle:"Relatório completo · PDF",reportP:"O cartão mostra onde estás. O relatório mostra o que fazer a seguir.",
  teaser:"Plano de 90 dias · Dias 1 a 30",unlock:"Desbloqueia com o teu email",
  name:"Nome",namePh:"O teu nome",workEmail:"Email de trabalho",emailPh:"nome@empresa.pt",
  optin:"Quero receber conteúdos da LayerX sobre adoção de IA.",
  getReport:"Receber o relatório",preparing:"A preparar o relatório…",
  fine:"Recebes o relatório aqui e por email. A LayerX guarda o teu email e o resultado do diagnóstico para te enviar o relatório e, se aceitares, conteúdos sobre IA.",
  badEmail:"Escreve um email válido, por exemplo nome@empresa.pt.",
  generating:"A gerar o relatório…",genFail:"Não foi possível gerar o relatório. Tenta de novo.",
  downloaded:"Relatório descarregado.",noDownloads:"Neste ecrã não é possível descarregar ficheiros. O relatório fica aqui em baixo.",
  saved:"Relatório guardado.",dlCancelled:"Download cancelado.",dlBusy:"Já há um download a decorrer. Tenta de novo daqui a pouco.",
  dlFail:"Não foi possível descarregar aqui. O relatório fica aqui em baixo.",pageAlt:i=>`Relatório, página ${i}`,
  fileName:s=>`relatorio-ai-mirror-${s}.pdf`,slugFallback:"empresa",
  mail_sending:e=>`A enviar o relatório também para ${e}…`,
  mail_sent:e=>`Enviámos também o relatório para ${e}.`,
  mail_failed:()=>"Não foi possível enviar o relatório por email. Podes descarregá-lo aqui.",
  contactTitle:"Tens alguma dúvida?",
  contactP:"Escreve-nos sobre o diagnóstico, o relatório ou a tua situação. A equipa da LayerX responde por email.",
  message:"Mensagem",messagePh:"Em que te podemos ajudar?",send:"Enviar mensagem",sending:"A enviar…",
  emptyMsg:"Escreve a tua mensagem.",
  sent:e=>`Mensagem enviada. Respondemos para ${e} em breve.`,
  sendFail:e=>`Não foi possível enviar a mensagem. Tenta de novo ou escreve para ${e}.`,
  // PDF
  pdfLabel1:"RELATÓRIO AI MIRROR",pdfFoot:"LayerX · AI Mirror",pdfNameFallback:"A tua empresa",
  pdfIndex:"ÍNDICE AI READY",pdfArch:"ARQUÉTIPO",pdfArchAnalysis:"ANÁLISE DO ARQUÉTIPO",
  pdfRisk:"MAIOR RISCO",pdfFocus:"ONDE FOCAR",pdfSuper:"SUPERPODER",pdfAchilles:"CALCANHAR DE AQUILES",
  pdfLabel2:"OS 8 EIXOS EM DETALHE",pdfAxesTitle:"Os 8 eixos em detalhe",pdfAxesSub:"Do mais fraco para o mais forte. Começa pelo topo.",
  pdfLabel3:"BENCHMARK E PLANO",pdfBenchTitle:"Benchmark e plano de 90 dias",
  pdfVsSector:s=>`A TUA EMPRESA VS. MÉDIA ESTIMADA DO SETOR ${s.toUpperCase()}`,
  pdfLegend:"Barra: a tua empresa  ·  Marca branca: média estimada do setor  ·  Valor: diferença em pontos",
  pdfCompanies:"EMPRESAS MAIS PARECIDAS",pdfSectors:"SETORES MAIS PRÓXIMOS",pdfPlan:"PLANO DE 90 DIAS",
  pdfPhases:["Dias 1 a 30","Dias 31 a 60","Dias 61 a 90"],
  pdfNote:"Perfis de referência estimados pela LayerX a partir de informação pública. Marca uma conversa: ",
 },
 axes:{
  est:{name:"Estratégia",desc:"A IA está na agenda da liderança",strong:"Liderança alinhada",weak:"Falta direção",
   i:["A IA ainda não tem lugar na agenda da liderança, por isso cada iniciativa depende de quem a puxa.","Há intenção e alguns objetivos, mas falta transformar a vontade num plano com dono e orçamento.","A IA tem patrocínio claro e objetivos mensuráveis. A estratégia está a liderar a transformação."],
   r:["Nomear um responsável pela IA e escolher 3 casos de uso com dono e KPI para os próximos 90 dias.","Converter os objetivos num roadmap trimestral com responsáveis, orçamento e métricas de sucesso.","Rever o portefólio de casos de uso a cada trimestre e cortar o que não mostra retorno."]},
  ado:{name:"Adoção",desc:"As pessoas usam IA no dia a dia",strong:"Equipas que já usam",weak:"Uso ainda raro",
   i:["O uso de IA é pontual e quase sempre em contas pessoais, o que esconde ganhos e cria risco.","Parte das equipas já usa IA, mas o uso é desigual e pouco partilhado.","A IA faz parte do trabalho diário da maioria das pessoas."],
   r:["Dar licenças empresariais a uma equipa piloto e medir o tempo poupado ao fim de 30 dias.","Alargar as licenças a toda a empresa e criar uma biblioteca interna de prompts e casos que funcionam.","Passar do uso individual para fluxos de equipa, com IA integrada nas ferramentas que já usam."]},
  pro:{name:"Processos",desc:"Há IA em produção, não só pilotos",strong:"IA em produção",weak:"Pilotos que não escalam",
   i:["Ainda não há IA em processos reais e o valor fica no uso individual.","Existem pilotos, mas o caminho até produção não é claro e muitos ficam pelo caminho.","Vários processos já correm com IA em produção."],
   r:["Escolher um processo repetitivo e de baixo risco e levá-lo de piloto a produção em 6 semanas.","Definir critérios de passagem a produção (qualidade, custo, risco) e um dono para cada piloto.","Medir o impacto por processo e replicar o padrão nas áreas que ainda não automatizaram."]},
  dad:{name:"Dados",desc:"Informação organizada e acessível",strong:"Dados prontos a usar",weak:"Dados dispersos",
   i:["A informação crítica está dispersa em emails, folhas de cálculo e pessoas. É o maior travão à IA.","Há sistemas centrais, mas os dados ainda não estão documentados nem fáceis de consultar.","Os dados estão organizados e acessíveis, prontos a alimentar modelos e agentes."],
   r:["Mapear onde vive a informação crítica e centralizar primeiro a fonte que alimenta o caso de uso prioritário.","Documentar as fontes principais e criar uma camada de acesso única, com permissões claras.","Investir na qualidade e atualização contínua dos dados e abrir o acesso a novos casos de uso."]},
  tec:{name:"Tecnologia",desc:"Sistemas e equipa capazes de integrar",strong:"Base técnica sólida",weak:"Sistemas fechados",
   i:["Os sistemas são fechados e não há quem integre soluções de IA.","Parte dos sistemas está acessível e há alguma capacidade técnica, ainda insuficiente para escalar.","A base técnica permite integrar IA nos sistemas core com autonomia."],
   r:["Identificar um parceiro técnico e expor por API o sistema que suporta o caso de uso prioritário.","Reforçar a equipa com perfis de integração e uniformizar a forma de ligar modelos aos sistemas.","Criar uma plataforma interna reutilizável (modelos, agentes, avaliação) para acelerar cada novo caso."]},
  pes:{name:"Pessoas",desc:"Formação e cultura que valorizam o uso",strong:"Cultura de aprendizagem",weak:"Pouca formação",
   i:["Sem formação, cada pessoa aprende sozinha e o uso de IA é visto com desconfiança.","Há curiosidade e alguma formação, mas sem um percurso por função.","As pessoas estão preparadas e a cultura premeia quem usa e partilha."],
   r:["Fazer uma sessão de literacia em IA para toda a empresa e nomear um champion em cada equipa.","Desenhar formação por função, com casos práticos do dia a dia de cada equipa.","Reconhecer e divulgar os melhores casos internos e dar tempo protegido para experimentar."]},
  gov:{name:"Governança",desc:"Regras, risco e AI Act",strong:"Risco sob controlo",weak:"Regras por definir",
   i:["Não há regras de uso nem visibilidade sobre que dados entram em ferramentas de IA.","Existem algumas regras, mas o risco e o AI Act ainda não estão mapeados.","A governança está montada e acompanha a adoção."],
   r:["Escrever uma política de uso de IA de uma página e listar os dados que nunca podem sair da empresa.","Mapear os casos de uso por nível de risco à luz do AI Act e formar as equipas na política.","Automatizar o controlo (registo de casos, revisões periódicas) para não travar a velocidade."]},
  inv:{name:"Investimento",desc:"Orçamento e medição de impacto",strong:"Investimento com retorno",weak:"Sem orçamento nem métricas",
   i:["Não há orçamento dedicado nem medição, e a IA compete por recursos caso a caso.","Há algum investimento, mas o impacto é medido por perceção.","O investimento cresce suportado por ROI medido."],
   r:["Reservar orçamento para 2 pilotos e definir à partida a métrica de sucesso de cada um.","Definir KPIs por caso de uso (tempo, custo, receita) e rever os resultados todos os meses.","Alocar orçamento por retorno comprovado e reservar uma fatia para apostas de maior risco."]},
 },
 bands:["Inicial","Em curso","Avançado"],
 sectors:["Banca e seguros","Indústria","Retalho e consumo","Tecnologia","Saúde","Logística e transportes","Serviços profissionais","Setor público","Energia e utilities","Turismo e hotelaria","Telecomunicações","Outro"],
 questions:[
  {q:"Em que setor está a tua empresa?"},
  {q:"Quantas pessoas trabalham na empresa?",o:["1 a 10","11 a 50","51 a 250","Mais de 250"]},
  {q:"Qual é a tua função?",o:["Administração / C-level","Gestão intermédia","Perfil técnico","Outra"]},
  {q:"A IA aparece na estratégia da empresa?",o:["Não se fala disso","Fala-se, mas sem plano","Há objetivos definidos para este ano","Tem dono, orçamento e KPIs"]},
  {q:"Quem lidera a IA na empresa?",o:["Ninguém","Iniciativa individual de alguns","Uma área ou equipa","A administração, com patrocínio explícito"]},
  {q:"Que percentagem das pessoas usa IA generativa todas as semanas?",o:["Menos de 10%","Entre 10% e 30%","Entre 30% e 60%","Mais de 60%"]},
  {q:"Que ferramentas de IA usam?",o:["Contas pessoais gratuitas","Licenças pagas para alguns","Licenças empresariais para todos","IA integrada nos sistemas internos"]},
  {q:"Quantos processos têm IA em produção?",o:["Nenhum","Um piloto","Entre 2 e 5","Mais de 5"]},
  {q:"O que acontece a um piloto de IA que funciona?",o:["Não fazemos pilotos","Fica no PowerPoint","Às vezes escala","Há um caminho definido até produção"]},
  {q:"Onde vive a informação crítica da empresa?",o:["Em emails, Excels e na cabeça das pessoas","Em vários sistemas desligados","Em sistemas centrais, com algum acesso","Centralizada, documentada e acessível por API"]},
  {q:"Se pedires hoje as vendas por cliente dos últimos 3 anos, quanto tempo demoram a dar-tas?",o:["Semanas","Dias","Horas","Já estão num dashboard"]},
  {q:"Os sistemas core têm APIs ou estão na cloud?",o:["Não","Poucos","A maioria","Todos, com acesso programático"]},
  {q:"Quem integraria uma solução de IA nos vossos sistemas?",o:["Ninguém","Um fornecedor externo, pontualmente","Alguns perfis internos","Uma equipa dedicada"]},
  {q:"Que formação em IA existe na empresa?",o:["Nenhuma","Cada um aprende sozinho","Sessões pontuais","Programa estruturado por função"]},
  {q:"Como é visto quem usa IA no trabalho?",o:["Com desconfiança","Ninguém sabe que usa","É tolerado","É celebrado e partilhado"]},
  {q:"Existe uma política de uso de IA?",o:["Não","Informal","Escrita","Escrita, com formação e revista regularmente"]},
  {q:"Em relação ao AI Act e aos dados sensíveis…",o:["Não sabemos o que é","Sabemos, mas ainda não fizemos nada","Mapeámos os riscos","Temos um processo de compliance"]},
  {q:"Que orçamento anual existe para IA?",o:["Zero","Ad hoc, quando surge","Uma linha dedicada","Crescente, justificado por ROI"]},
  {q:"Medem o impacto da IA?",o:["Não","Por perceção","Com alguns KPIs","ROI por caso de uso"]},
  {q:"Se a IA desaparecesse amanhã, a empresa…",o:["Nem notava","Alguns ficavam chateados","Perdia produtividade visível","Parava operações"]},
 ],
 arch:{
  native:{name:"AI-Native",tag:"A IA já é o sistema operativo da empresa.",
   desc:"A IA está na estratégia, no dia a dia e nos sistemas. O desafio agora é manter a vantagem: escolher bem onde investir a seguir e medir o retorno com rigor.",
   risk:"Complacência: a vantagem de hoje desaparece se a empresa deixar de experimentar.",focus:"Escalar com disciplina de ROI e levar agentes a processos críticos."},
  rebelde:{name:"O Rebelde",tag:"Toda a gente usa, ninguém controla.",
   desc:"As equipas adotaram IA mais depressa do que a empresa conseguiu organizar-se. Há energia e ganhos reais, mas também dados a sair por ferramentas pessoais e pouca visibilidade sobre o impacto.",
   risk:"Fuga de dados e decisões tomadas com ferramentas sem controlo.",focus:"Canalizar a energia: licenças empresariais, política clara e casos de uso oficiais."},
  observador:{name:"O Observador",tag:"Ainda a ver para onde vai o vento.",
   desc:"A IA ainda não entrou na empresa de forma consistente. É o ponto de partida mais comum e também o mais barato para começar bem: um caso de uso escolhido com critério chega para mudar a conversa.",
   risk:"Ficar para trás enquanto a concorrência ganha produtividade e aprende mais depressa.",focus:"Um caso de uso com valor visível em 90 dias e literacia básica para toda a equipa."},
  visionario:{name:"O Visionário de Slides",tag:"A estratégia está pronta, falta o resto.",
   desc:"Há vontade e patrocínio da liderança, mas os dados, os sistemas e os processos ainda não acompanham. A ambição corre o risco de se gastar em pilotos que nunca chegam a produção.",
   risk:"Pilotos que nunca chegam a produção por falta de base técnica.",focus:"Arrumar dados e sistemas para o primeiro caso de uso chegar a produção."},
  engenheiro:{name:"O Engenheiro Silencioso",tag:"Terreno fértil, falta direção.",
   desc:"A base técnica está melhor do que a maioria: dados, sistemas e regras. Falta a liderança apontar o caminho e as pessoas ganharem o hábito. Com uma prioridade clara, avança depressa.",
   risk:"Capacidade técnica parada à espera de uma prioridade de negócio.",focus:"Patrocínio da liderança e 2 ou 3 prioridades claras."},
  construtor:{name:"O Construtor",tag:"A IA já faz parte da casa.",
   desc:"A empresa passou da experimentação à adoção. Há casos em produção, pessoas que usam e alguma disciplina. O próximo salto é escalar o que funciona e reforçar os eixos que ficaram para trás.",
   risk:"Crescimento desigual, com eixos atrasados a travar a escala.",focus:"Replicar o que funciona e reforçar os eixos mais fracos."},
  explorador:{name:"O Explorador",tag:"Já começou a viagem, falta o mapa.",
   desc:"Há experiências e algum uso, mas ainda sem uma direção partilhada. É a fase em que escolher 2 ou 3 prioridades faz mais diferença do que fazer mais coisas.",
   risk:"Dispersão: muitas experiências, pouco impacto acumulado.",focus:"Escolher 2 ou 3 prioridades e dar-lhes dono, orçamento e métrica."},
 },
 levels:["Nível 1 · Arranque","Nível 2 · Experimentação","Nível 3 · Adoção","Nível 4 · Escala","Nível 5 · AI-Native"],
},

en:{
 htmlLang:"en",locale:"en-GB",
 title:"AI Mirror · LayerX",
 metaDesc:"Free assessment: how AI ready is your company? 20 questions, 8 axes, your archetype and a 90-day plan.",
 ui:{
  langLabel:"Language",navLabel:"Main navigation",nav:{quiz:"AI Mirror",companies:"Companies",countries:"Countries"},
  rankingsTitle:"Global AI adoption rankings",
  rankings:[["/rankings/empresas","Ranking · Companies","Which large companies are most advanced in AI?","The 500 S&P 500 companies assessed by the AIDE Index 2026."],
            ["/rankings/paises","Ranking · Countries","Where in the world is AI used most?","147 economies in the Microsoft AI Diffusion Report. See where your country ranks."]],
  rankingsLink:"See ranking →",
  resumeKicker:"Assessment in progress",resumeTitle:"Pick up where you left off",
  resumeBody:(n,t)=>`You've answered ${n} of ${t} questions. Your answers are saved in this browser.`,
  resumeKickerDone:"Assessment complete",resumeTitleDone:"Your result is saved",
  resumeBodyDone:"You've answered every question. Your answers are saved in this browser.",
  resumeContinue:"Continue →",resumeSeeResult:"See result →",resumeRestart:"Start over",
  eyebrow:"AI Mirror · Free assessment · LayerX",
  h1:'How <span class="gtext">AI ready</span> is your company?',
  lead:"20 questions, about 4 minutes. At the end you see your company's profile across 8 axes, your archetype and who you resemble. If you like, you also get a report with an action plan.",
  companyLabel:"Company name (optional, shown on your card)",
  companyPh:"E.g. Northern Metalworks",
  start:"Start assessment →",
  meta:["20 questions","8 axes","7 archetypes"],
  axesPreview:"The 8 axes · example",axesPreviewAria:"The 8 axes measured",
  tagProfile:"Profile",tagBonus:"Bonus",
  back:"Previous",home:"Start",keyHint:"1–4 to answer · ← back",
  computing:"Calculating your 8 axes…",
  radarAria:"Radar of the 8 axes",
  people:"people",
  cardHead:"MY RESULT",scoreLbl:"AI Ready",closest:"Most similar to",compatible:"match",
  yourAxes:"Your 8 axes",otherCompanies:"Other companies",nearSectors:"Closest sectors",
  superpower:"Superpower",achilles:"Achilles' heel",cardFootL:"Find your profile",
  shareNote:"Take a screenshot of the card to share on LinkedIn or in your stories.",
  ctaText:"Want to turn this assessment into a concrete plan? Talk to LayerX's AI Consulting team for 30 minutes.",
  ctaBtn:"Book a call ↗",redo:"↺ Retake the assessment",
  toc:[["Your archetype analysis","What defines your company, the biggest risk and where to focus"],
       ["The 8 axes in detail","Diagnosis and recommendation for each axis"],
       null,
       ["90-day plan","Three steps, in order, starting with the weakest axis"]],
  tocSector:s=>"Comparison with the "+s+" sector",tocBench:"Benchmark against companies and sectors",tocBenchSub:"Where you are above and below the reference",
  reportReady:"Your report is ready",
  reportReadyP:n=>`3-page PDF report with the action plan for ${n}.`,yourCompany:"your company",
  download:"Download PDF report",
  reportTitle:"Full report · PDF",reportP:"The card shows where you are. The report shows what to do next.",
  teaser:"90-day plan · Days 1 to 30",unlock:"Unlock with your email",
  name:"Name",namePh:"Your name",workEmail:"Work email",emailPh:"name@company.com",
  optin:"I'd like to receive LayerX content on AI adoption.",
  getReport:"Get the report",preparing:"Preparing your report…",
  fine:"You get the report here and by email. LayerX stores your email and assessment result to send you the report and, if you agree, content about AI.",
  badEmail:"Enter a valid email, for example name@company.com.",
  generating:"Generating your report…",genFail:"The report could not be generated. Please try again.",
  downloaded:"Report downloaded.",noDownloads:"Files can't be downloaded on this screen. The report is shown below.",
  saved:"Report saved.",dlCancelled:"Download cancelled.",dlBusy:"A download is already in progress. Try again in a moment.",
  dlFail:"The report couldn't be downloaded here. It is shown below.",pageAlt:i=>`Report, page ${i}`,
  fileName:s=>`ai-mirror-report-${s}.pdf`,slugFallback:"company",
  mail_sending:e=>`Also sending the report to ${e}…`,
  mail_sent:e=>`We've also sent the report to ${e}.`,
  mail_failed:()=>"We couldn't email the report. You can download it here.",
  contactTitle:"Any questions?",
  contactP:"Write to us about the assessment, the report or your situation. The LayerX team will reply by email.",
  message:"Message",messagePh:"How can we help?",send:"Send message",sending:"Sending…",
  emptyMsg:"Write your message.",
  sent:e=>`Message sent. We'll reply to ${e} soon.`,
  sendFail:e=>`The message could not be sent. Try again or write to ${e}.`,
  // PDF
  pdfLabel1:"AI MIRROR REPORT",pdfFoot:"LayerX · AI Mirror",pdfNameFallback:"Your company",
  pdfIndex:"AI READY SCORE",pdfArch:"ARCHETYPE",pdfArchAnalysis:"ARCHETYPE ANALYSIS",
  pdfRisk:"BIGGEST RISK",pdfFocus:"WHERE TO FOCUS",pdfSuper:"SUPERPOWER",pdfAchilles:"ACHILLES' HEEL",
  pdfLabel2:"THE 8 AXES IN DETAIL",pdfAxesTitle:"The 8 axes in detail",pdfAxesSub:"From weakest to strongest. Start at the top.",
  pdfLabel3:"BENCHMARK AND PLAN",pdfBenchTitle:"Benchmark and 90-day plan",
  pdfVsSector:s=>`YOUR COMPANY VS. ESTIMATED ${s.toUpperCase()} SECTOR AVERAGE`,
  pdfLegend:"Bar: your company  ·  White mark: estimated sector average  ·  Value: difference in points",
  pdfCompanies:"MOST SIMILAR COMPANIES",pdfSectors:"CLOSEST SECTORS",pdfPlan:"90-DAY PLAN",
  pdfPhases:["Days 1 to 30","Days 31 to 60","Days 61 to 90"],
  pdfNote:"Reference profiles estimated by LayerX from public information. Book a call: ",
 },
 axes:{
  est:{name:"Strategy",desc:"AI is on the leadership agenda",strong:"Aligned leadership",weak:"Lack of direction",
   i:["AI has no place on the leadership agenda yet, so every initiative depends on whoever pushes it.","There is intent and some goals, but the will still needs to become a plan with an owner and a budget.","AI has clear sponsorship and measurable goals. Strategy is leading the transformation."],
   r:["Appoint an AI lead and pick 3 use cases, each with an owner and a KPI, for the next 90 days.","Turn the goals into a quarterly roadmap with owners, budget and success metrics.","Review the use case portfolio every quarter and cut what doesn't show a return."]},
  ado:{name:"Adoption",desc:"People use AI day to day",strong:"Teams already using it",weak:"Usage still rare",
   i:["AI use is occasional and mostly on personal accounts, which hides gains and creates risk.","Some teams already use AI, but usage is uneven and rarely shared.","AI is part of the daily work of most people."],
   r:["Give enterprise licences to a pilot team and measure the time saved after 30 days.","Extend licences to the whole company and build an internal library of prompts and proven cases.","Move from individual use to team workflows, with AI built into the tools people already use."]},
  pro:{name:"Processes",desc:"AI in production, not just pilots",strong:"AI in production",weak:"Pilots that don't scale",
   i:["There is no AI in real processes yet, and the value stays in individual use.","There are pilots, but the path to production is unclear and many stall along the way.","Several processes already run with AI in production."],
   r:["Pick a repetitive, low-risk process and take it from pilot to production in 6 weeks.","Define go-to-production criteria (quality, cost, risk) and an owner for each pilot.","Measure impact per process and replicate the pattern in areas that haven't automated yet."]},
  dad:{name:"Data",desc:"Organised, accessible information",strong:"Data ready to use",weak:"Scattered data",
   i:["Critical information is scattered across emails, spreadsheets and people. It is the biggest brake on AI.","There are central systems, but the data isn't documented or easy to query yet.","Data is organised and accessible, ready to feed models and agents."],
   r:["Map where critical information lives and first centralise the source that feeds the priority use case.","Document the main sources and create a single access layer with clear permissions.","Invest in ongoing data quality and freshness, and open access to new use cases."]},
  tec:{name:"Technology",desc:"Systems and team able to integrate",strong:"Solid technical base",weak:"Closed systems",
   i:["Systems are closed and nobody can integrate AI solutions.","Some systems are accessible and there is some technical capacity, still not enough to scale.","The technical base lets you integrate AI into core systems on your own."],
   r:["Find a technical partner and expose via API the system behind the priority use case.","Strengthen the team with integration profiles and standardise how models connect to systems.","Build a reusable internal platform (models, agents, evaluation) to speed up each new case."]},
  pes:{name:"People",desc:"Training and a culture that values use",strong:"Learning culture",weak:"Little training",
   i:["Without training, everyone learns alone and AI use is viewed with suspicion.","There is curiosity and some training, but no learning path per role.","People are prepared and the culture rewards those who use and share."],
   r:["Run an AI literacy session for the whole company and name a champion in each team.","Design role-based training with practical cases from each team's daily work.","Recognise and share the best internal cases and give protected time to experiment."]},
  gov:{name:"Governance",desc:"Rules, risk and the AI Act",strong:"Risk under control",weak:"Rules still undefined",
   i:["There are no usage rules and no visibility on what data goes into AI tools.","Some rules exist, but risk and the AI Act haven't been mapped yet.","Governance is in place and keeps pace with adoption."],
   r:["Write a one-page AI usage policy and list the data that must never leave the company.","Map use cases by risk level under the AI Act and train teams on the policy.","Automate oversight (use case register, periodic reviews) so it doesn't slow you down."]},
  inv:{name:"Investment",desc:"Budget and impact measurement",strong:"Investment with return",weak:"No budget or metrics",
   i:["There is no dedicated budget or measurement, and AI competes for resources case by case.","There is some investment, but impact is judged by perception.","Investment grows, backed by measured ROI."],
   r:["Set aside budget for 2 pilots and define each one's success metric up front.","Define KPIs per use case (time, cost, revenue) and review results every month.","Allocate budget by proven return and keep a slice for higher-risk bets."]},
 },
 bands:["Early","In progress","Advanced"],
 sectors:["Banking and insurance","Manufacturing","Retail and consumer","Technology","Healthcare","Logistics and transport","Professional services","Public sector","Energy and utilities","Tourism and hospitality","Telecoms","Other"],
 questions:[
  {q:"What sector is your company in?"},
  {q:"How many people work at the company?",o:["1 to 10","11 to 50","51 to 250","More than 250"]},
  {q:"What is your role?",o:["Board / C-level","Middle management","Technical role","Other"]},
  {q:"Does AI feature in the company's strategy?",o:["It isn't discussed","It's discussed, but there's no plan","There are defined goals for this year","It has an owner, budget and KPIs"]},
  {q:"Who leads AI in the company?",o:["Nobody","A few individuals on their own initiative","A department or team","The board, with explicit sponsorship"]},
  {q:"What share of people use generative AI every week?",o:["Less than 10%","Between 10% and 30%","Between 30% and 60%","More than 60%"]},
  {q:"Which AI tools do you use?",o:["Free personal accounts","Paid licences for some","Enterprise licences for everyone","AI built into internal systems"]},
  {q:"How many processes have AI in production?",o:["None","One pilot","Between 2 and 5","More than 5"]},
  {q:"What happens to an AI pilot that works?",o:["We don't run pilots","It stays in a PowerPoint","Sometimes it scales","There's a defined path to production"]},
  {q:"Where does the company's critical information live?",o:["In emails, spreadsheets and people's heads","In several disconnected systems","In central systems, with some access","Centralised, documented and accessible via API"]},
  {q:"If you asked today for sales by customer over the last 3 years, how long would it take to get them?",o:["Weeks","Days","Hours","They're already in a dashboard"]},
  {q:"Do your core systems have APIs or run in the cloud?",o:["No","A few","Most of them","All, with programmatic access"]},
  {q:"Who would integrate an AI solution into your systems?",o:["Nobody","An external supplier, occasionally","A few internal people","A dedicated team"]},
  {q:"What AI training exists in the company?",o:["None","Everyone learns on their own","Occasional sessions","A structured programme by role"]},
  {q:"How are people who use AI at work seen?",o:["With suspicion","Nobody knows they use it","It's tolerated","It's celebrated and shared"]},
  {q:"Is there an AI usage policy?",o:["No","Informal","Written","Written, with training and regular reviews"]},
  {q:"When it comes to the AI Act and sensitive data…",o:["We don't know what it is","We know, but haven't done anything yet","We've mapped the risks","We have a compliance process"]},
  {q:"What annual budget is there for AI?",o:["Zero","Ad hoc, as needs arise","A dedicated line","Growing, justified by ROI"]},
  {q:"Do you measure AI's impact?",o:["No","By perception","With some KPIs","ROI per use case"]},
  {q:"If AI disappeared tomorrow, the company would…",o:["Not even notice","Have a few people annoyed","Lose visible productivity","Stop operating"]},
 ],
 arch:{
  native:{name:"AI-Native",tag:"AI is already the company's operating system.",
   desc:"AI is in the strategy, in daily work and in the systems. The challenge now is to keep the edge: choose carefully where to invest next and measure the return rigorously.",
   risk:"Complacency: today's edge disappears if the company stops experimenting.",focus:"Scale with ROI discipline and bring agents into critical processes."},
  rebelde:{name:"The Rebel",tag:"Everyone uses it, nobody controls it.",
   desc:"Teams adopted AI faster than the company could organise itself. There is energy and real gains, but also data leaking through personal tools and little visibility on impact.",
   risk:"Data leaks and decisions made with uncontrolled tools.",focus:"Channel the energy: enterprise licences, a clear policy and official use cases."},
  observador:{name:"The Observer",tag:"Still watching which way the wind blows.",
   desc:"AI hasn't entered the company consistently yet. It's the most common starting point and also the cheapest place to start well: one carefully chosen use case is enough to change the conversation.",
   risk:"Falling behind while competitors gain productivity and learn faster.",focus:"One use case with visible value in 90 days and basic literacy for the whole team."},
  visionario:{name:"The Slide-Deck Visionary",tag:"The strategy is ready, the rest isn't.",
   desc:"There is will and leadership sponsorship, but data, systems and processes haven't caught up. The ambition risks being spent on pilots that never reach production.",
   risk:"Pilots that never reach production for lack of a technical base.",focus:"Get data and systems in order so the first use case reaches production."},
  engenheiro:{name:"The Silent Engineer",tag:"Fertile ground, no direction yet.",
   desc:"The technical base is better than most: data, systems and rules. What's missing is leadership pointing the way and people building the habit. With a clear priority, it moves fast.",
   risk:"Technical capacity sitting idle, waiting for a business priority.",focus:"Leadership sponsorship and 2 or 3 clear priorities."},
  construtor:{name:"The Builder",tag:"AI is already part of the house.",
   desc:"The company has moved from experimentation to adoption. There are cases in production, people using AI and some discipline. The next leap is to scale what works and shore up the axes that lag behind.",
   risk:"Uneven growth, with lagging axes holding back scale.",focus:"Replicate what works and strengthen the weakest axes."},
  explorador:{name:"The Explorer",tag:"The journey has started, the map is missing.",
   desc:"There are experiments and some use, but no shared direction yet. This is the stage where picking 2 or 3 priorities makes more difference than doing more things.",
   risk:"Dispersion: many experiments, little accumulated impact.",focus:"Pick 2 or 3 priorities and give them an owner, a budget and a metric."},
 },
 levels:["Level 1 · Starting","Level 2 · Experimenting","Level 3 · Adopting","Level 4 · Scaling","Level 5 · AI-Native"],
},
};
